### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by chjohnkim** [amy-tabb/RWHEC-Tabb-AhmadYousef#6]
Hi @amy-tabb , thank you for sharing your great work. 
I was trying to perform handeye calibration on our robot and camera with your project. The reprojected images seem to be correct, but the translation of the transformation (Z-matrix) seems to be completely wrong. I saw that you mentioned a "bug with regards to the computation of the translation error" in your README. Could you share what the bug was and how I can debug it?
Thank you again for your work.

**Comment by amy-tabb** [comment]
Hi, 
The bug with the translation error was fixed in the summer of 2018, and that bug did not affect the computation of X or Z.  It did affect one of  the tables generated, though.  

You can take a look at the full paper + erratum here -- https://arxiv.org/pdf/1907.12425.pdf which details the changes.

Guessing -- the formulation I used switches the usual meaning of X and Z, so take a look at Figure 1 in the paper.  

Also, this may (or may not!) be helpful -- to use the calibration with robot encoder info represented in HTM B, you can create a new camera position A-hat via A-hat = ZB(X.inverse()).  This is similar to the cost function in Equation 9. 

Let me know if any of this information is helpful. Again, there's no bugs in the code to my knowledge at the moment.

Best, 
Amy

**Comment by chjohnkim** [comment]
Thank you for your help, I took a look at the paper and realized my mistake of not inverting the B matrix (matrix from robot base to hand). This solved my issue. Thank you again for your help and wonderful work.

**Comment by amy-tabb** [comment]
Oh, awesome.  I love the easy solutions!  Really, let me know if you have other issues.
